name: flutter_gifimage
description: A GifImage widget for Flutter allowing you to control the speed and progress of the GIF.
version: 1.1.0
homepage: https://github.com/peng8350/flutter_gifimage

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:


